# Introduction to NumPy (Numerical Python)

## Overview
* NumPy is the fundamental package for scientific computing with Python
  * See the [NumPy Home Page](http://www.numpy.org/)
  
### Do Now!
* Import NumPy
* View the NumPy help page

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

## NumPy is huge!
* Development of NumPy started in the mid-90s
* See the Wikipedia article on [NumPy's history](https://en.wikipedia.org/wiki/NumPy#History) for details


## About *ndarray*
* NumPy provides the class *ndarray*
* This contain single dimensional and multidimensional arrays
## *ndarray*s vs. *list*s and *array.array*s
* Compared to *list*s, *ndarray*s are:
  * more space efficient
  * less flexible
    * *list*s can hold heterogeneous data
  * more performant
  * able to be used to solve the same type of problems
    * *list*s and *ndarray*s can hold data in multidimensions

* Compared to *array.array*s, *ndarray*s are: 
  * similar in space efficiency
  * identical in requiring data to be homogeneous
  * similar in their run-time performance
  * able to be used with more general problems
    * *array.array*s can hold data in only one dimension

In [4]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

## What can be done with Arrays?
* Arrays can be: 
  * Created
  * Manipulated (Joining, Spliting, Shaping, etc.)
  * Accessed one element at a time
  * Accessed via array slices
  * Reshaped
  * Split
  * Concatenated

# Creating Arrays

## Using the *array* Function to Create *ndarrays*
* Although it is possible to create an *ndarray* instance using \_\_new\_\_(), it is not the recommended approach
* The factory methods *array*, *zeros*, *ones*, and *empty* are preferred
* The *array* factory method is discussed here

### Do Now!
* Import numpy
* View the doc string of the numpy array function

In [ ]:
import numpy as np

In [ ]:
help(np.array)

## The array function will copy the source collection into a numpy array object and automatically determine the data type

In [7]:
data1 = [1, 2, 3, 4]
array1 = np.array(data1)
print(data1)
print(array1)
print(type(array1))
print(array1.dtype)


[1, 2, 3, 4]
[1 2 3 4]
<class 'numpy.ndarray'>
int64


## Since there is a single float in this collection it determines that is the most appropriate data type for the numpy array

In [33]:
data2 = [1.0, 2, 3, 4]
array2 = np.array(data2)
print(array2)
print(array2.dtype)


['1.0' '2' '3' '4' '10']
<U32


## You can specify the dtype parameter to force a preferred data type

In [15]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [22]:
from numpy import int32, float32
data3 = [1, 2, 3, 4]
array3 = np.array(data3, dtype = 'float128')
print(array3)
print(array3.dtype)
print(array3.shape)
print(len(array3))

[1. 2. 3. 4.]
float128
(4,)
4


## If the collection is a collection of other collections, it will create a multi-dimensional numpy array

In [32]:
data4 = [[1,2,3,4],[5,6,7,8]]
array4 = np.array(data4)
print(array4)
print(array4.dtype)
print(array4.shape, len(array4), array4.size)

data40 = [[[1,2,3,4],[5,6,7,8]], 
          [[10,20,30,40], [50,60,70, 80]]]
array40 = np.array(data40)
print(array40.shape, array40.size, array40.dtype)
print(array40)

[list([1, 2, 3, 4]) list([5, 6, 7])]
object
(2,) 2 2
(2, 2, 4) 16 int64
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [50 60 70 80]]]


## Summary of useful *ndarray* attributes
* For convenience, here a list of *ndarray* attributes
* Given x = np.ones( (2,3,4,5), dtype='float128')
   * ndim, the number of dimensions; e.g., 4
   * shape, the size of each dimension; e.g., (2,3,4,5)
   * dtype, the data type of each element; e.g., np.float128
   * itemsize, the size of each element 
        * Determined by the dtype; e.g., 16 bytes
   * size, the total number of elements in the array
        * Determined by the product of the shape sizes; e.g., 2 \* 3 \* 4 \* 5 = 120
   * nbytes, the total size of the array
        * Determine by the product of size and itemsize; e.g., 120 * 16 = 1920
   * strides, the number of bytes traversed in order to move from element to element in one dimension or across dimensions

In [35]:
#np.array(range(10))
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Using the *zeros* Function to Create *ndarrays*
* The *zeros* function, as its name suggest, creates an *ndarray* containing all zeros
* Unlike the *array* function, *zeros* doesn't take source data
* *zeros* includes a *shape* parameter for specifying the dimensions of the created *ndarray*


In [36]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [53]:
z1 = np.zeros(4, dtype = int)
o1 = np.ones((2,4), dtype = int)
e1 = np.empty((2,4))

print(z1, z1.shape, z1.dtype)
print(o1, o1.shape, o1.dtype)
print(e1, e1.shape, e1.dtype)

z1[0] = 10
z1[-1] = 20
z1[1:3] = 30
z1[:] = 40
print(z1)

e1[:] = -1
print(e1)

e1[0:2] = -2
print(e1)

[0 0 0 0] (4,) int64
[[1 1 1 1]
 [1 1 1 1]] (2, 4) int64
[[5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]] (2, 4) float64
[40 40 40 40]
[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]
[[-2. -2. -2. -2.]
 [-2. -2. -2. -2.]]


## LAB 1: ## 
#### 1.	Define an ndarray containing the integer numbers 0 to 9.
#### 2.	Print the type of the array to the console.
#### 3.	Print the following properties of the array:
    a.	ndim
    b.	shape
    c.	size
    
#### 4.	Define a 3 x 3 NumPy array containing all 1s of integer type and display it to the console.
#### 5.	Print the three properties of Step 3 on the array defined in Step 4.

<br>

<details><summary>Click for <b>code</b></summary>
<p>

```python
import numpy as np
a1 = np.arange(10)
print(a1)
print(a1.dtype, a1.ndim, a1.shape, a1.size)

a2 = np.ones((3,3), dtype='int32')
print(a2)
print(a2.dtype, a2.ndim, a2.shape, a2.size)

```
</p>
</details>

In [56]:
import numpy as np
a1 = np.arange(1, 11, 2)
print(a1)
print(a1.dtype, a1.ndim, a1.shape, a1.size)

a2 = np.ones((3,3), dtype='int32')
print(a2)
print(a2.dtype, a2.ndim, a2.shape, a2.size)


[1 3 5 7 9]
int64 1 (5,) 5
[[1 1 1]
 [1 1 1]
 [1 1 1]]
int32 2 (3, 3) 9


## Instead of using the python range function and converting it into a numpy array, you could directly create a numpy array using the arange function

In [ ]:
help(np.arange)

In [57]:
print ("arange array = ", np.arange(5, 25, 4))

arange array =  [ 5  9 13 17 21]


### *np.linspace*
* View the doc string for *np.linspace*
* Print an array of 50 numbers spaced over the interval 1 to 25

In [66]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [65]:
print ("Evenly spaced array = ", np.linspace(1,10, 101))
x = np.linspace(1,25)
print(type(x), x.dtype, len(x), x.size, x.shape)

Evenly spaced array =  [ 1.    1.09  1.18  1.27  1.36  1.45  1.54  1.63  1.72  1.81  1.9   1.99
  2.08  2.17  2.26  2.35  2.44  2.53  2.62  2.71  2.8   2.89  2.98  3.07
  3.16  3.25  3.34  3.43  3.52  3.61  3.7   3.79  3.88  3.97  4.06  4.15
  4.24  4.33  4.42  4.51  4.6   4.69  4.78  4.87  4.96  5.05  5.14  5.23
  5.32  5.41  5.5   5.59  5.68  5.77  5.86  5.95  6.04  6.13  6.22  6.31
  6.4   6.49  6.58  6.67  6.76  6.85  6.94  7.03  7.12  7.21  7.3   7.39
  7.48  7.57  7.66  7.75  7.84  7.93  8.02  8.11  8.2   8.29  8.38  8.47
  8.56  8.65  8.74  8.83  8.92  9.01  9.1   9.19  9.28  9.37  9.46  9.55
  9.64  9.73  9.82  9.91 10.  ]
<class 'numpy.ndarray'> float64 50 50 (50,)


## You can add a simple scalar value to an array and it will have the effect of adding it to each elements
### Note the difference if you do a multiply operation to a python list instead

In [71]:
array1 = np.array([[1,2,3],[4,5,6]])
print(dir(array1))
print(dir(list))
print(array1 + 10)

print(array1 ** 2)

print([1, 2, 3] * 10)

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

## Arrays of compatible shapes can also be operated on

In [78]:
print(array1)
# print(array1 + array1)
# print(array1 * array1)

array2 = np.array([10, 20, 30])
print(array2.shape)
print(array1 * array2)

# This is the wrong shape
# array3 = np.array([10, 20])
# print(array1 * array3)

array4 = np.array([[10], [20]])
print(array4.shape)
print(array1 * array4)


[[1 2 3]
 [4 5 6]]
(3,)
[[ 10  40  90]
 [ 40 100 180]]
(2, 1)
[[ 10  20  30]
 [ 80 100 120]]


## Slicing is similar to how it behaves in a python collection with a few twists

In [84]:
array1 = np.arange(12)
print(array1)
print(array1[2])
print(array1[2:5])
array1[2:5] = 99
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
2
[2 3 4]
[ 0  1 99 99 99  5  6  7  8  9 10 11]


## When you have a multi-dimensional array it can start to be a bit different

In [109]:
array2d = np.array([[1,2],[3,4],[5,6]])
print(array2d)
# print(array2d[1], type(array2d[1]))      # returns the entire second element --> [3,4]
# print(array2d[1][0])   # returns the second elements then takes the first element of that
# print(array2d[1,0])    # returns the element at second row first column
print(array2d[0:2])
print(array2d[0:2][0]) # returns the first two elements, then the first element of that
print(array2d[0:2,1])  # returns the slice of the first two rows and the first column of each of those rows

array2d = np.array([[1,2,10],[3,4,20],[5,6,30]])
print(array2d[:,-2:])


[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[1 2]
[2 4]
[[ 2 10]
 [ 4 20]
 [ 6 30]]


## You can reshape arrays from one to two dimensions and vice versa so long as the dimensions make sense for the number of elements in the array

In [121]:
array1 = np.arange(20).reshape((4,5))
print(array1)
array2 = array1.reshape(20)
print(array2)
array3 = array1.reshape(2,10)
print(array3)
print(array1.size)


print(array1.reshape(array1.size))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
20
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [118]:
#print('abcdef'[::-1])

print(array1)
#print(array1[:,:])
print(array1[:,::-1])
print(array1[:,:3])

print(array1[:,::-1][:,:3])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]]
[[ 4  3  2]
 [ 9  8  7]
 [14 13 12]
 [19 18 17]]


## You can flatten an array to one dimension with either ravel or flatten. Ravel only makes a copy if necessary whereas flatten always makes a copy

In [125]:
help(array1.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function
    
    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.



In [122]:
array3 = array1.ravel()
print(array3)
array4 = array1.flatten()
print(array4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Transposing is the process of flipping an array 90 degrees and is easy to do in numpy

In [124]:
print(array1)
print(array1.shape)
print(array1.T)
print(array1.T.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
(5, 4)


In [127]:
dir(array1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [131]:
help(array1.sum)

Help on built-in function sum:

sum(...) method of numpy.ndarray instance
    a.sum(axis=None, dtype=None, out=None, keepdims=False)
    
    Return the sum of the array elements over the given axis.
    
    Refer to `numpy.sum` for full documentation.
    
    See Also
    --------
    numpy.sum : equivalent function



In [133]:
print(array1)
# print(array1.sum(), array1.mean(), array1.max())
# print(array1.cumsum())
# print(np.sum(array1))
print(array1.sum(axis=0)) # column sum
print(array1.sum(axis=1)) # row sum
print(array1.sum(axis=None)) 


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[30 34 38 42 46]
[10 35 60 85]
190


## LAB 2: ## 
#### 1.	Define a 3 x 3 array with the integers 1 through 9 named array1.
#### 2.	Define a second 3 x 3 array with the number 2 in each cell named array2.
#### 3.	Now, perform the following operations using the two arrays:
    a.	array1+array2
    b.	array1-array2
    c.	array1/array2
    d.	array1*5
#### 4.	Print elements 4 to 6 of array 1 using a slice operation.
#### 5.	Create a new single-dimensioned array named array3 with the numbers 0 through 19 in it.
#### 6.	Take a slice of elements 5 to 15 of array 3 and assign the slice to a variable named aslice and print the variable.
#### 7.	Modify the contents of the first and last elements of the slice by writing the value 99 into these elements.
#### 8.	Print the contents of the slice aslice and the array array3. Are the contents what you expect of both arrays?
<br>
<details><summary>Click for <b>hint</b></summary>
<p>
Use empty to create an array and set all values to 2 using a slice syntax. Make sure to use integers data types.
<br>
To set the elements from the right of a slice use negative numbers. Don't forget the index starts at zero on the left.
<br>
<br>
</p>
</details>


<details><summary>Click for <b>code</b></summary>
<p>

```python
array1 = np.arange(1, 10).reshape((3,3))
print(array1)
array2 = np.empty((3,3), dtype='int32')
array2[:] = 2
print(array2)

print(array1 + array2)
print(array1 - array2)
print(array1 / array2)
print(array1 + 5)

print(array1.reshape((9,))[4:6])

array3 = np.arange(0, 20)
aslice = array3[5:15]
print(aslice)
aslice[0] = 99
aslice[-1] = 99
print(aslice)
print(array3)
```
</p>
</details>

In [139]:
array1 = np.arange(1, 10, dtype = int).reshape(3,3)
print(array1)
array2 = np.empty((3,3), dtype='int32')
array2[:] = 2
print(array2)

print(array1 + array2)
print(array1 - array2)
print(array1 / array2)
print(array1 + 5)

print(array1.reshape((9,))[4:7])

array3 = np.arange(0, 20)
aslice = array3[5:15]
print(aslice)
aslice[0] = 99
aslice[-1] = 99
print(aslice)
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[5 6 7]
[ 5  6  7  8  9 10 11 12 13 14]
[99  6  7  8  9 10 11 12 13 99]
[ 0  1  2  3  4 99  6  7  8  9 10 11 12 13 99 15 16 17 18 19]


## You can read and write from files into numpy arrays

In [140]:
array1 = np.arange(10)
np.save('array1.npy', array1)
array2 = np.load('array1.npy')
print(array2)
! cat array1.npy

[0 1 2 3 4 5 6 7 8 9]
�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (10,), }                                                           
	

## File archives allow you to store multiple numpy arrays into one file. It's sort of like a saved dictionary

In [141]:
array1 = np.arange(10)
array2 = 2 * array1
np.savez('array_archive.npz', data_set_1=array1, data_set_2=array2)
archive = np.load('array_archive.npz')
print(archive['data_set_1'])
print(archive['data_set_2'])

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


## If you want to read or write from plain text files instead of the numpy serialized file format, there is another set of methods for that

In [147]:
array2d = np.array([[1,2,3],[4,5,6]], dtype=int)
print(array2d.dtype)
np.savetxt('array_data.txt', array2d, delimiter=',', fmt='%5.0f')
array2d_from_file = np.loadtxt('array_data.txt', delimiter=',', dtype=int)
print(array2d_from_file)
! cat array_data.txt

int64
[[1 2 3]
 [4 5 6]]
    1,    2,    3
    4,    5,    6


In [149]:
array2d = np.array([[1,2,3],[4,5,6]], dtype=int)
print(array2d.astype(float))


[[1. 2. 3.]
 [4. 5. 6.]]


## With NumPy, multiplying two two-dimensional arrays with * is an element-wise product, not a matrix dot product

In [ ]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[1,2,3],[4,5,6]])
array_multiply = array1 * array2
print(array_multiply)

## The dot method will do the cross multiply dot product used in a lot of complex algorithms

In [151]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[1,2],[3,4],[5,6]])
print(array1)
print(array2)
array_dot_product = array1.dot(array2)
print(array_dot_product)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]


In [153]:
import scipy as sp
dir(sp)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'LowLevelCallable',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_UFUNC_API',
 '__SCIPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__numpy_version__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '_distributor_init',
 '

## Examples of random number generation

In [155]:
from numpy.linalg import inv
array1 = np.array([[.1,.2,.3],[.4,.5,.6], [.7,.8,.9]])
array2 = inv(array1)

print(array1 * array2)

[[-6.74335773e+14  2.69734309e+15 -2.02300732e+15]
 [ 5.39468618e+15 -1.34867155e+16  8.09202928e+15]
 [-4.72035041e+15  1.07893724e+16 -6.06902196e+15]]


In [159]:
#print (np.random.normal(5, 2, 90)) # mean = 5, std = 2
print (np.random.uniform(1, 100, 8).astype(int)) # low = 1, high = 100
print (np.random.poisson(10, 10)) # 10 numbers averaging to 10

[91 74 11 34 72  6  3 50]
[ 8  8 12  7 10 12  8 10  9  5]


## Sometimes a function does not have a dtype parameter directly, but you can use the astype method to cast it to what you want

In [160]:
array1 = np.random.uniform(1, 100, 8)
print(array1)
array2 = array1.astype(int)
print(array2)

[11.33955654 17.6065499   8.18982163 13.00600675 28.92908827 64.73825805
  7.93215891 90.37022319]
[11 17  8 13 28 64  7 90]


In [164]:
np.random.seed(1)
print(np.random.uniform(1, 100, 8).astype(int))
print(np.random.uniform(1, 100, 8).astype(int))

[42 72  1 30 15 10 19 35]
[40 54 42 68 21 87  3 67]


## Homework: ## 
#### 1.	Generate 20 random integers between 1 and 100
#### 2.	Print the mean of those numbers
#### 3.	Turn those 20 numbers into a 4 x 5 matrix
#### 4. Transpose the matrix into a new variable
#### 5.	Find the dot product of the matrix and its transposed version
#### 6. Solve the simultaneous equations:
     10x + 20y = 50
     30x + 40y = 60
<br>
<details><summary>Click for <b>hint</b></summary>
<p>
Look at help on np.random. There are more choices than what we did in the slides.
<br>
To solve simultaneous equations look at np.linalg.solve
<br>
<br>
</p>
</details>

