## Homework: ## 
#### 1.	Generate 20 random integers between 1 and 100
#### 2.	Print the mean of those numbers
#### 3.	Turn those 20 numbers into a 4 x 5 matrix
#### 4. Transpose the matrix into a new variable
#### 5.	Find the dot product of the matrix and its transposed version
#### 6. Solve the simultaneous equations:
     10x + 20y = 50
     30x + 40y = 60
<br>
<details><summary>Click for <b>hint</b></summary>
<p>
Look at help on np.random. There are more choices than what we did in the slides.
<br>
To solve simultaneous equations look at np.linalg.solve
<br>
<br>
</p>
</details>



In [11]:
import numpy as np
np.random.seed(1)
a0 = np.random.uniform(1, 100, 20).astype(int)
print(a0)

np.random.seed(1)
a1 = np.random.randint(1, 100, 20)
print(a1)

print(a1.mean())

a2 = a1.reshape((4, 5))
print(a2)

print(a1.reshape((5, 4)))

a3 = a2.T
print(a3)

print(a2.dot(a3))

x1 = np.array([[10, 20],[30, 40]])
y1 = np.array([50, 60])
print(np.linalg.solve(x1, y1))

[42 72  1 30 15 10 19 35 40 54 42 68 21 87  3 67 42 56 14 20]
[38 13 73 10 76  6 80 65 17  2 77 72  7 26 51 21 19 85 12 29]
38.95
[[38 13 73 10 76]
 [ 6 80 65 17  2]
 [77 72  7 26 51]
 [21 19 85 12 29]]
[[38 13 73 10]
 [76  6 80 65]
 [17  2 77 72]
 [ 7 26 51 21]
 [19 85 12 29]]
[[38  6 77 21]
 [13 80 72 19]
 [73 65  7 85]
 [10 17 26 12]
 [76  2 51 29]]
[[12818  6335  8509  9574]
 [ 6335 10954  7221  7433]
 [ 8509  7221 14439  5371]
 [ 9574  7433  5371  9012]]
[-4.   4.5]
