## LAB 1: ## 
#### 1.	Define an ndarray containing the integer numbers 0 to 9.
#### 2.	Print the type of the array to the console.
#### 3.	Print the following properties of the array:
    a.	ndim
    b.	shape
    c.	size
    
#### 4.	Define a 3 x 3 NumPy array containing all 1s of integer type and display it to the console.
#### 5.	Print the three properties of Step 3 on the array defined in Step 4.

<br>

<details><summary>Click for <b>code</b></summary>
<p>

```python
import numpy as np
a1 = np.arange(10)
print(a1)
print(a1.dtype, a1.ndim, a1.shape, a1.size)

a2 = np.ones((3,3), dtype='int32')
print(a2)
print(a2.dtype, a2.ndim, a2.shape, a2.size)

```
</p>
</details>

## LAB 2: ## 
#### 1.	Define a 3 x 3 array with the integers 1 through 9 named array1.
#### 2.	Define a second 3 x 3 array with the number 2 in each cell named array2.
#### 3.	Now, perform the following operations using the two arrays:
    a.	array1+array2
    b.	array1-array2
    c.	array1/array2
    d.	array1*5
#### 4.	Print elements 4 to 6 of array 1 using a slice operation.
#### 5.	Create a new single-dimensioned array named array3 with the numbers 0 through 19 in it.
#### 6.	Take a slice of elements 5 to 15 of array 3 and assign the slice to a variable named aslice and print the variable.
#### 7.	Modify the contents of the first and last elements of the slice by writing the value 99 into these elements.
#### 8.	Print the contents of the slice aslice and the array array3. Are the contents what you expect of both arrays?
<br>
<details><summary>Click for <b>hint</b></summary>
<p>
Use empty to create an array and set all values to 2 using a slice syntax. Make sure to use integers data types.
<br>
To set the elements from the right of a slice use negative numbers. Don't forget the index starts at zero on the left.
<br>
<br>
</p>
</details>


<details><summary>Click for <b>code</b></summary>
<p>

```python
array1 = np.arange(1, 10).reshape((3,3))
print(array1)
array2 = np.empty((3,3), dtype='int32')
array2[:] = 2
print(array2)

print(array1 + array2)
print(array1 - array2)
print(array1 / array2)
print(array1 + 5)

print(array1.reshape((9,))[4:6])

array3 = np.arange(0, 20)
aslice = array3[5:15]
print(aslice)
aslice[0] = 99
aslice[-1] = 99
print(aslice)
print(array3)
```
</p>
</details>

## Homework: ## 
#### 1.	Generate 20 random integers between 1 and 100
#### 2.	Print the mean of those numbers
#### 3.	Turn those 20 numbers into a 4 x 5 matrix
#### 4. Transpose the matrix into a new variable
#### 5.	Find the dot product of the matrix and its transposed version
#### 6. Solve the simultaneous equations:
     10x + 20y = 50
     30x + 40y = 60
<br>
<details><summary>Click for <b>hint</b></summary>
<p>
Look at help on np.random. There are more choices than what we did in the slides.
<br>
To solve simultaneous equations look at np.linalg.solve
<br>
<br>
</p>
</details>



In [0]:
import numpy as np
a1 = np.random.randint(1, 100, 20)
print(a1)

print(a1.mean())

a2 = a1.reshape((4,5))
print(a2)

a3 = a2.T
print(a3)

print(a2.dot(a3))

x1 = np.array([[10, 20],[30, 40]])
y1 = np.array([50, 60])
print(np.linalg.solve(x1, y1))

[99  8 99 14 48 29 47 13 59 75 82 85 99 40 21 86 84  2 98 97]
59.25
[[99  8 99 14 48]
 [29 47 13 59 75]
 [82 85 99 40 21]
 [86 84  2 98 97]]
[[99 29 82 86]
 [ 8 47 85 84]
 [99 13 99  2]
 [14 59 40 98]
 [48 75 21 97]]
[[22166  8960 20167 15412]
 [ 8960 12325 11595 19525]
 [20167 11595 25791 20347]
 [15412 19525 20347 33469]]
[-4.   4.5]
